config/routes.rb
Rails.application.routes.draw do
  get 'profiles/my_cars'
  devise_for :users
  root to: 'pages#home'
  resources :cars do
    resources :rentings, only: %i[new create show]
  end
  get "/my_cars", to: "profiles#my_cars"
  get "/my_rentings", to: "profiles#my_rentings"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord
  has_many :rentings, dependent: :destroy
  belongs_to :user

  has_one_attached :photo

  validates :brand, presence: true
  validates :model, presence: true
  validates :description, presence: true, length: { minimum: 30 }
  validates :seats, presence: true, numericality: { only_integer: true, greater_than: 0, less_than_or_equal_to: 20 }
  validates :photo, presence: true
end

app/models/renting.rb
class Renting < ApplicationRecord
  belongs_to :user
  belongs_to :car

  validates :date, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :cars
  has_many :rentings
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :photo

  validates :username, presence: true, uniqueness: true
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :location, presence: true
  validates :photo, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name username age location photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: %i[first_name last_name username age location photo])
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  skip_before_action :authenticate_user!, only: :index
  def index
    @cars = Car.all
  end

  def show
    id = params[:id]
    @car = Car.find(id)
  end

  def new
    @car = Car.new
  end

  def create
    @car = Car.new(car_params)
    @car.user = current_user
    if @car.save
      redirect_to car_path(@car)
    else
      render :new
    end
  end

  def edit
    @car = Car.find(params[:id])
  end

  def destroy
    @car = Car.find(params[:id])
    @car.destroy
    redirect_to my_cars_path, notice: "Your car has been deleted."
  end

  private

  def car_params
    params.require(:car).permit(:brand, :model, :seats, :description, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  def my_cars
    @cars = current_user.cars
  end

  def my_rentings
    @rentings = current_user.rentings
  end
end

app/controllers/rentings_controller.rb
class RentingsController < ApplicationController
  before_action :set_car, only: %i[new create]

  def show
    @car = Car.find(params[:car_id])
    @renting = Renting.find(params[:id])
  end

  def new
    @renting = Renting.new
  end

  def create
    @renting = Renting.new(renting_params)
    @renting.user = current_user
    @renting.car = @car
    if @renting.save
      redirect_to car_renting_path(@car, @renting)
    else
      render :new
    end
  end

  private

  def set_car
    @car = Car.find(params[:car_id])
  end

  def renting_params
    params.require(:renting).permit(:date)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cars/_car_card.html.erb
<div class="card-product">
  <%= cl_image_tag car.photo.key %>
  <div class="card-product-infos">
    <h2><%= car.model %></h2>
    <p><%= car.description %></p>
  </div>
</div>

app/views/cars/index.html.erb
<div class="banner-small" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(http://stars-h2020.eu/wp-content/uploads/2018/03/Photo-INEA-Project-Fiche.png);">
  <div class="container">
  <h1>Sharing is Caring</h1>
  <p>Your local eco-friendly car service</p>
  </div>
</div>
<br>

<div class="container-index">
  <h1 class="text-center">All Cars</h1>
  <br>
  <% @cars.each do |car| %>
    <%= link_to(car_path(car)) do %>
    <div class="card-product">
      <%= cl_image_tag car.photo.key %>
      <div class="card-product-infos">
        <h2><%= car.brand %> <%= car.model %></h2>
        <p><%= car.description %></p>
      </div>
    </div>
    <% end %>
  <br>
  <% end %>

  <div class="text-center">
    <%= link_to "Back to Homepage", root_path, class: "btn btn-secondary"%>
  </div>
</div>

app/views/cars/new.html.erb
<div class="container">
  <h1> Create a new car <%= image_tag("https://icon-library.com/images/car-icon-front/car-icon-front-15.jpg", width: "50", height: "40")  %> </h1>
  <div class="input-form">
    <%= simple_form_for(@car) do |f| %>
      <%= f.input :brand %>
      <%= f.input :model %>
      <%= f.input :seats %>
      <%= f.input :description %>
      <%= f.input :photo, as: :file %>
      <%= f.submit class: "btn btn-success" %>
    <% end %>
  </div>

  <div class="display=flex text-center">
    <%= link_to "See all cars", cars_path, class: "btn btn-secondary"%>
  </div>
</div>

app/views/cars/show.html.erb
<div class="container-show">
  <div class="banner-car" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= cl_image_path @car.photo.key%>);">
  </div>
  <div class="car-description">
    <div class="car-info">
      <h2><%= @car.brand %> <%= @car.model %></h2>
      <h5> <%= cl_image_tag @car.user.photo.key, class: "avatar" %>   <%= @car.user.first_name.capitalize %> <%= @car.user.last_name.capitalize %></h5>
      <p><%= @car.description%></p>
      <p><i class="fas fa-male"></i><i class="fas fa-male"></i><i class="fas fa-male"></i>  <%= @car.seats %> Seater </p>
    </div>
    <% if current_user != @car.user %>
    <%= link_to "Rent this car", new_car_renting_path(@car), class: "btn btn-success rent-button"%>
    <% end %>
  </div>
  <div class="text-center back-button">
    <%= link_to "See all cars", cars_path, class: "btn btn-secondary"%>
  </div>
 </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SharingIsCaring</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css">
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <div class="page-container">
      <div class="navbar-container"><%= render "shared/navbar" %></div>
      <div class="content-container"><%= yield %></div>
      <div class="footer-container"><%= render "shared/footer" %></div>
      <%= render 'shared/flashes' %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(http://stars-h2020.eu/wp-content/uploads/2018/03/Photo-INEA-Project-Fiche.png);">
  <div class="container">
  <h1>Sharing is Caring</h1>
  <p>Your local eco-friendly car service</p>
      <%= link_to "Available Cars", cars_path, class: "btn btn-flat" %>
  </div>
</div>

app/views/profiles/my_cars.html.erb
<div class="banner-small" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(http://stars-h2020.eu/wp-content/uploads/2018/03/Photo-INEA-Project-Fiche.png);">
  <div class="container">
  <h1>Sharing is Caring</h1>
  <p>Your local eco-friendly car service</p>
  </div>
</div>
<br>

<div class="container-index">
  <h2 class="text-center"><%= current_user.first_name.capitalize %> <%= current_user.last_name.capitalize %>'s cars</h2>
  <% @cars.each do |car| %>
    <%= link_to(car_path(car)) do %>
    <div class="card-product">
      <%= cl_image_tag car.photo.key %>
      <div class="card-product-infos">
        <h4><%= car.brand %> <%= car.model %></h4>
        <p> <%= car.description %> </p>
        <div class="action-buttons">
         <%= link_to "Delete", car_path(car), method: :delete,
            data: { confirm: "Are you sure?" } %>
          <%= link_to "Edit", car_path(car), method: :delete,
            data: { confirm: "Are you sure?" } %>
        </div>
      </div>
    </div>
    <% end %>
  <br>
  <% end %>

  <div class="text-center">
    <%= link_to "Back to Homepage", root_path, class: "btn btn-secondary"%>
  </div>
</div>

app/views/profiles/my_rentings.html.erb
<div class="banner-small" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(http://stars-h2020.eu/wp-content/uploads/2018/03/Photo-INEA-Project-Fiche.png);">
  <div class="container">
  <h1>Sharing is Caring</h1>
  <p>Your local eco-friendly car service</p>
  </div>
</div>
<br>

<div class="container-index">
  <h2 class="text-center"><%= current_user.first_name.capitalize %> <%= current_user.last_name.capitalize %>'s rentings</h2>
  <% @rentings.each do |renting| %>
    <%= link_to(car_path(renting.car)) do %>
    <div class="card-product">
      <%= cl_image_tag renting.car.photo.key %>
      <div class="card-product-infos">
        <h4><%= renting.car.brand %> <%= renting.car.model %></h4>
        <p> On the <%= renting.date %> </p>
      </div>
    </div>
    <% end %>
  <br>
  <% end %>

  <div class="text-center">
    <%= link_to "Back to Homepage", root_path, class: "btn btn-secondary"%>
  </div>
</div>

app/views/rentings/new.html.erb
<div class="container">
  <div class="rent-your-car">
    <h1> Rent your car <%= image_tag("https://icon-library.com/images/car-icon-front/car-icon-front-15.jpg", width: "50", height: "40")  %> </h1>
    <div class="input-form">
      <%= simple_form_for [@car, @renting] do |f| %>
        <%= f.input :date, as: :string, input_html: { id: "flatpickr", class: "d-none" } %>
        <%= f.submit "Rent car", class: "btn btn-success new-renting-button" %>
      <% end %>
    </div>
    <br>
    <br>
    <br>
    <div class="display=flex text-center">
      <%= link_to "See all cars", cars_path, class: "btn btn-secondary"%>
      <%= link_to "Check car details", car_path(@car), class: "btn btn-secondary"%>
    </div>
  </div>
</div>

app/views/rentings/show.html.erb
<div class="container">
  <div class="receipt text-center">
    <h1>Your Renting</h1>
    <%= cl_image_tag @car.photo.key, width: "100%" %>
    <div class="receipt-description">
      <p><i class="fas fa-calendar-week"></i> <%= @renting.date %></p>
      <%= link_to(car_path(@car)) do %>
      <p>Your Car: <%= @car.brand %> <%= @car.model %></p>
      <% end %>
    </div>
  </div>




  <div class="display=flex text-center">
    <%= link_to "See all cars", cars_path, class: "btn btn-secondary"%>
    <%= link_to "Back to Homepage", root_path, class: "btn btn-secondary"%>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="github.com"><i class="fab fa-github"></i></a>
    <a href="instagram.com"><i class="fab fa-instagram"></i></a>
    <a href="facebook.com"><i class="fab fa-facebook"></i></a>
    <a href="twitter.com"><i class="fab fa-twitter"></i></a>
    <a href="linkedin.com"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    © 2021 SharingIsCaring. All rights reserved
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "https://assets.adac.de/image/upload/c_scale,f_auto,q_auto:eco,t_16:9-default,w_2000/v1/ADAC-eV/KOR/Bilder/RF/car-sharing-2-2011_hcy2wn" %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "/", class: "nav-link" %>
        </li>
        <li class="nav-item active">
          <%= link_to "Add Car", new_car_path, class: "nav-link" %>
        </li>
        <li class="nav-item active">
          <%= link_to current_user.username, edit_user_registration_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "My Rentings", "/my_rentings", class: "dropdown-item" %>
            <%= link_to "My Cars", "/my_cars", class: "dropdown-item" %>
            <%= link_to "Add Car", new_car_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>